import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from './ThemeContext'; // Import the ThemeProvider
import CustomAppBar from './AppBar'; // Import the CustomAppBar component if it's used here
import FlashcardPage from './flashcard/page'; // Import other pages/components if needed
import GeneratePage from './generate/page'; // Import other pages/components if needed
import FlashcardsPage from './flashcards/page';
import HomePage from './page.js';
const inter = Inter({ subsets: ["latin"] });
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
    <ClerkProvider>
      <html lang="en">
        <head>
       
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GOOGLE_ANALYTICS_MEASUREMENT_ID}`}
            strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive" >
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());


              gtag('config', '${process.env.GOOGLE_ANALYTICS_MEASUREMENT_ID}');
            `}
          </Script>
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
    </ThemeProvider>
  );
}
